### ISSUE TITLE
旧版聊天室无法在热门房间发言，但3-19的端口仍然可以发言

### ISSUE THREAD

**Issue by MisaLiu** [ShiSheng233/How_to_Fxxk_Weilei_s_Server#2]
昨天kurisu反馈了3-19端口无法发送消息的is，然后在看到消息后我就~~那~~拿自己写的轰炸机简单测试了一下，发现仍然可以发送消息。
然后我刚才又测试了一下，发现还是可以发送消息。
![image](https://user-images.githubusercontent.com/62408957/77127647-43929d80-6a88-11ea-8209-1d0a37062674.png)
不知道是不是玄学问题。
不过还请大佬多加注意！
——小白 Misa Liu

**Comment by iiismile** [comment]
我说的他会提示盗链，我估计有**不一样的链接**。

**Comment by MisaLiu** [comment]
> 我说的他会提示盗链，我估计有**不一样的链接**。

双霖不是扒出来了新链接吗？我就是用他给出的端口写的轰炸机，一切正常

**Comment by ShiSheng233** [comment]
据我分析是服务端的限制，
我在每次请求时都会返回{"status":"ok"}
即：信息发送成功，但是服务端过滤了信息。

**Comment by MisaLiu** [comment]
> 据我分析是服务端的限制，
> 我在每次请求时都会返回{"status":"ok"}
> 即：信息发送成功，但是服务端过滤了信息。

有换IP试试吗？

**Comment by ShiSheng233** [comment]
是的，当ip被限制时不会有返回值，大多数时候会有400或者500的错误码返回
